# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5598517502c73db2b1f0e6948821c0bc5fed302e36098bf5930e6cd937100aae551402db8e24a339f8cb1f84dcc516aed7cdfd3ba6d8caf21b974c0d6808088

test:
  secret_key_base: b04fe67e2adc20715a3dc31c932eaf230d212126a20755adf8c997fccd63d846b816526dc93beea06d9bcc8341972142a57abb4053fe1566d2b507f8da545fb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
